version: "3.9"

services:

  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8863:8863
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/citasbancarias
      - DATABASE_USERNAME=userdata
      - DATABASE_PASSWORD=123456
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres